# datasource
spring:
  datasource:
    url: jdbc:mysql:///mp?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.itheima.mybatis_springboot.domain
